# Generated by Django 2.1.5 on 2019-02-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstype',
            old_name='prifile',
            new_name='operation_type',
        ),
        migrations.RenameField(
            model_name='businesstype',
            old_name='type',
            new_name='profile',
        ),
    ]
