# Generated by Django 2.1.5 on 2019-02-24 11:15

from django.db import migrations, models
def load_options(apps, schema_editor):
    OperationType = apps.get_model("eventify", "OperationType")
    operation_type = OperationType(name='Building Materials & Services')
    operation_type.save()
    operation_type = OperationType(name='Business & Personal Services')
    operation_type.save()
    operation_type = OperationType(name='Clothing')
    operation_type.save()
    operation_type = OperationType(name='Entertainment')
    operation_type.save()
    operation_type = OperationType(name='Financial Services')
    operation_type.save()
    operation_type = OperationType(name='Food & Drink')
    operation_type.save()
    operation_type = OperationType(name='General Retail & High Street')
    operation_type.save()
    operation_type = OperationType(name='Health')
    operation_type.save()
    operation_type = OperationType(name='Motoring')
    operation_type.save()
    operation_type = OperationType(name='Petrol')
    operation_type.save()
    operation_type = OperationType(name='Restaurants')
    operation_type.save()
    operation_type = OperationType(name='Services')
    operation_type.save()
    operation_type = OperationType(name='Restaurants')
    operation_type.save()
    operation_type = OperationType(name='Supermarket')
    operation_type.save()
    operation_type = OperationType(name='Training & Education')
    operation_type.save()
    operation_type = OperationType(name='Travel')
    operation_type.save()

    Profile = apps.get_model("eventify", "Profile")
    profile = Profile(name='Premium')
    profile.save()
    profile = Profile(name='Standard')
    profile.save()
    profile = Profile(name='Ekonomiczna')
    profile.save()

    YearlyMaxRevenue = apps.get_model("eventify", "YearlyMaxRevenue")
    yearly_max_revenue = YearlyMaxRevenue(revenue=10000)
    yearly_max_revenue.save()
    yearly_max_revenue = YearlyMaxRevenue(revenue=100000)
    yearly_max_revenue.save()
    yearly_max_revenue = YearlyMaxRevenue(revenue=1000000)
    yearly_max_revenue.save()

    Area = apps.get_model("eventify", "Area")
    area = Area(name='WARSZAWA')
    area.save()
    area = Area(name='Warszawa (Bemowo)')
    area.save()
    area = Area(name='Warszawa (Białołęka)')
    area.save()
    area = Area(name='Warszawa (Bielany)')
    area.save()
    area = Area(name='Warszawa (Mokotów)')
    area.save()
    area = Area(name='Warszawa (Ochota)')
    area.save()
    area = Area(name='Warszawa (Praga-Południe)')
    area.save()
    area = Area(name='Warszawa (Praga-Północ)')
    area.save()
    area = Area(name='Warszawa (Rembertów)')
    area.save()
    area = Area(name='Warszawa (Targówek)')
    area.save()
    area = Area(name='Warszawa (Ursus)')
    area.save()
    area = Area(name='Warszawa (Ursynów)')
    area.save()
    area = Area(name='Warszawa (Wawer)')
    area.save()
    area = Area(name='Warszawa (Wesoła)')
    area.save()
    area = Area(name='Warszawa (Wilanów)')
    area.save()
    area = Area(name='Warszawa (Wola)')
    area.save()
    area = Area(name='Warszawa (Włochy)')
    area.save()
    area = Area(name='Warszawa (Śródmieście)')
    area.save()
    area = Area(name='Warszawa (Śródmieście)')
    area.save()

def delete_options(apps, schema_editor):
    OperationType = apps.get_model("eventify", "OperationType")
    OperationType.objects.all().delete()
    Profile= apps.get_model("eventify", "Profile")
    Profile.objects.all().delete()
    YearlyMaxRevenue = apps.get_model("eventify", "YearlyMaxRevenue")
    YearlyMaxRevenue.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0003_auto_20190223_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
